package services

import "errors"

var (
	ErrUserNotFound     	 = errors.New("user not found")
	ErrEmailExists      	 = errors.New("email already exist")
	ErrInvalidPassword  	 = errors.New("invalid password")
	ErrValidationFailed 	 = errors.New("validation failed")
	ErrShortPassword    	 = errors.New("password is too short, must be more then 5 symbols!")
	ErrTooManyRequests  	 = errors.New("too many requests! (1 req/sec)")
	ErrContextCancelled 	 = errors.New("context was cancelled")
	ErrNoEvents         	 = errors.New("user has no events")
	ErrNoEventTitle 		 = errors.New("set the title for an event")
	ErrNoOwnerID 			 = errors.New("event dont have OwnerID")
	ErrEventNotFound 		 = errors.New("event does not exist")
	ErrEventNoParticipants   = errors.New("event has no participants")
	ErrNoEventsWithRole 	 = errors.New("no events with this role")
	ErrParticipantNotFound   = errors.New("participant not found")
	ErrAlreadyParticipant    = errors.New("user already participant of this event")
	ErrInvalidRole           = errors.New("invalid role assignment")
	ErrLastOwnerCannotLeave  = errors.New("last owner cannot leave event")
	ErrSelfRoleChange        = errors.New("cannot change your own role")
	ErrNotParticipant        = errors.New("user is not participant of this event")
	ErrNotOwner 			 = errors.New("there no owner")
	ErrDeleteLiveEvent 		 = errors.New("can not delete event when its already going live")
	ErrCantPublishEvent		 = errors.New("cant publish event")
	ErrCantDraftEvent 		 = errors.New("cant change event status to draft")
	ErrCantUpdateEvent 		 = errors.New("cant update event")
	ErrCantBeAssignToEvent	 = errors.New("cant be assign to event")
	ErrCantCancelEvent		 = errors.New("cant cancel event")
)